\set ON_ERROR_STOP on
\connect university

BEGIN;
CREATE SCHEMA lab7;
SET search_path TO lab7;

CREATE TABLE pk_column_example (
    student_id INTEGER PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(150)
);

CREATE TABLE pk_table_example (
    student_id INTEGER,
    name VARCHAR(100),
    email VARCHAR(150),
    PRIMARY KEY (student_id)
);

CREATE TABLE pk_named_example (
    student_id INTEGER,
    name VARCHAR(100),
    email VARCHAR(150),
    CONSTRAINT pk_named_example_key PRIMARY KEY (student_id)
);

CREATE TABLE pk_added_example (student_id INTEGER, name VARCHAR(100));
ALTER TABLE pk_added_example
    ADD CONSTRAINT pk_added_example_key PRIMARY KEY (student_id);

CREATE TABLE students (
    student_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE,
    faculty VARCHAR(50)
);

INSERT INTO students (name, email, faculty) VALUES
    ('Alice Johnson', 'alice@alatoo.edu.kg', 'Computer Science'),
    ('Bob Smith', 'bob@alatoo.edu.kg', 'Mathematics'),
    ('Carol Davis', 'carol@alatoo.edu.kg', 'Computer Science');

CREATE TABLE course_enrollments (
    student_id INTEGER,
    course_id INTEGER,
    semester VARCHAR(20),
    enrollment_date DATE DEFAULT CURRENT_DATE,
    grade CHAR(2),
    PRIMARY KEY (student_id, course_id, semester)
);

INSERT INTO course_enrollments (student_id, course_id, semester, grade) VALUES
    (1, 101, '2024-Spring', 'A'),
    (1, 102, '2024-Spring', 'B+'),
    (2, 101, '2024-Spring', 'A-'),
    (1, 101, '2024-Fall', 'A+');

CREATE TABLE products (
    product_id SERIAL PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2)
);

CREATE TABLE transactions (
    transaction_id BIGSERIAL PRIMARY KEY,
    amount DECIMAL(15,2),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders (
    order_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100),
    order_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100),
    email VARCHAR(150)
);

INSERT INTO customers (customer_id, customer_name, email)
VALUES (1000, 'VIP Customer', 'vip@example.com');

CREATE TABLE departments (
    dept_id INTEGER PRIMARY KEY,
    dept_name VARCHAR(100)
);
INSERT INTO departments VALUES (1, 'Computer Science');

DO $$
BEGIN
    BEGIN
        INSERT INTO departments VALUES (1, 'Mathematics');
        RAISE EXCEPTION 'Duplicate primary key was accepted';
    EXCEPTION WHEN unique_violation THEN
        RAISE NOTICE 'Duplicate primary key was rejected';
    END;
    BEGIN
        INSERT INTO departments VALUES (NULL, 'Physics');
        RAISE EXCEPTION 'NULL primary key was accepted';
    EXCEPTION WHEN not_null_violation THEN
        RAISE NOTICE 'NULL primary key was rejected';
    END;
END $$;

COMMIT;
